<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Simu_NT" Id="{9ea71bbd-eae6-4317-8eaf-7d51dd590fd6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Simu_NT
VAR_INPUT

END_VAR

VAR_OUTPUT
	iOUT_TC_Water_1			: INT;
	iOUT_TC_Water_2			: INT;
	iOUT_CJC_Value			: INT;
	iOUT_ToolID_Value		: INT;
	bOUT_WaterFlow_1		: BOOL;
	bOUT_WaterFlow_2		: BOOL;
	bOUT_AirPressure		: BOOL;
	bOUT_TC_Water_1_Error	: BOOL;
	bOUT_TC_Water_2_Error	: BOOL;
	bOUT_CJC_Error			: BOOL;
	bOUT_ToolID_Error		: INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">9L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>